spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
#          uri: https://gitee.com/why191314/config-server.git
          uri: https://github.com/why1314/config-server.git
          username: why1314
          password: w19bzdwsm1314
          basedir: F:/Temp/basedir
#  rabbitmq:
#    host: 192.168.211.129
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
      defaultZone: http://localhost:8764/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"